// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package objc.lang

/**
 * An exception that has to be used when runtime calls for method unimplemented in Mirror from protocol.
 */
public class ObjCOptionalMethodUnimplementedException <: Exception {}