// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cangjie_lang_LibraryLoader */

#ifndef _Included_cangjie_lang_LibraryLoader
#define _Included_cangjie_lang_LibraryLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cangjie_lang_LibraryLoader
 * Method:    nativeLoadCJLibrary
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cangjie_lang_LibraryLoader_nativeLoadCJLibrary
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
